language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
    - phpenv config-rm xdebug.ini || return 0
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini || return 0

install:
    - travis_retry composer self-update
    - travis_retry composer install
    - composer info -i

script:
  - phpunit

branches:
  only:
      - master
